apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: registry.gitlab.com/csc-rahti-group/gandalf-project:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gitlab-registry-secret
